name: show commit message
on:
  push:
      branches:
        - main

jobs: 
    print-commit-message:
        runs-on: ubuntu-latest
        steps:
          - name:  Checkout repository
            uses: actions/checkout@v3

          - name: print  commit message
            run: |
             echo "Commit message"
              echo "${{ github.event.head_commit.message }}"