name: show commit message
on:
  push:
      branches:
        - main
jobs: 
    print-commit-message:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3

          - name: Show commit message
            run: echo "Commit message: ${{ github.event.head_commit.message }}"